---
abstract: 'Shortcut functions for L<Catalyst> controllers'
author:
  - "Robert \"phaylon\" Sedlacek <rs@474.at>"
build_requires:
  Catalyst::Plugin::Session: 0
  Catalyst::Plugin::Session::State::Cookie: 0
  Catalyst::Plugin::Session::Store::FastMmap: 0
  Catalyst::Test: 0
  FindBin: 0
  HTTP::Request: 0
  Test::More: 0.62
  Test::WWW::Mechanize::Catalyst: 0
distribution_type: module
generated_by: 'Module::Install version 0.75'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: CatalystX-Imports
no_index:
  directory:
    - inc
    - t
provides:
  CatalystX::Imports:
    file: lib/CatalystX/Imports.pm
    version: 0.02
  CatalystX::Imports::Context:
    file: lib/CatalystX/Imports/Context.pm
  CatalystX::Imports::Context::Config:
    file: lib/CatalystX/Imports/Context/Config.pm
  CatalystX::Imports::Context::Default:
    file: lib/CatalystX/Imports/Context/Default.pm
  CatalystX::Imports::Vars:
    file: lib/CatalystX/Imports/Vars.pm
requires:
  Carp::Clan: 0
  Catalyst::Runtime: 5.7000
  Class::C3: 0.14
  Class::Inspector: 0
  Data::Alias: 0.08
  List::MoreUtils: 0.19
  Scalar::Util: 1.19
  Scope::Guard: 0
version: 0.02
